#1/....................................

# import module
# def say_hello(name):
#     return print(f"hello {name},kaise ho bhai")
# def say_bye(name):
#     return print(f"hello {name},kaise ho bhai")

#2/......................................

# person={"name":"preetam","age":23}


#3/............................
#inbuit library

# import math
# a=16
# print(math.sqrt(a))

#4/.............................

# from math import factorial
# a=4
# print(factorial(a))
